documentation:
  - changed-files:
    - any-glob-to-any-file: ['**/*.md', 'docs/**']

test:
  - changed-files:
    - any-glob-to-any-file: ['tests/**', '**/*.test.ts']

ci:
  - changed-files:
    - any-glob-to-any-file: ['.github/**']