name: Release

permissions: 
  contents: write
  id-token: write

on:
  push:
    branches: [main, develop]

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    if: |
      github.event.head_commit.author.name != 'arca-dependency-manager[bot]' &&
      !contains(github.event.head_commit.message, 'skip ci')
    
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

      - name: Instalar pnpm
        uses: pnpm/action-setup@v5

      - name: Setup Node & pnpm
        uses: actions/setup-node@v6
        with:
          node-version: 24.14.1
          cache: 'pnpm'

      - name: Instalar dependências
        run: pnpm install --frozen-lockfile

      - name: Build da Biblioteca
        run: pnpm build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
