name: Renovate

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

concurrency:
  group: renovate
  cancel-in-progress: true

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
<<<<<<< HEAD
      - uses: renovatebot/github-action@v40.3.6
=======
      - uses: renovatebot/github-action@v40.1.11
>>>>>>> daf6064 (merge (1.7.0 release) (#21))
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          autodiscover: true
