name: Renovate

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: renovatebot/github-action@v40.3.6
        with:
          token: ${{ steps.generate_token.outputs.token }}
        env:
          RENOVATE_REPOSITORIES: 'sabschyks/Arca'
          RENOVATE_PLATFORM: 'github'
          RENOVATE_GIT_AUTHOR: 'Arca Dependency Manager <262118762+arca-dependency-manager[bot]@users.noreply.github.com>'
